<h1 id="fpectl-floating-point-exception-control"> fpectl — Floating point exception control</h1> <div class="admonition note" id="module-fpectl"> <p class="admonition-title">Note</p> <p>The <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module is not built by default, and its usage is discouraged and may be dangerous except in the hands of experts. See also the section <a class="reference internal" href="#fpectl-limitations"><span class="std std-ref">Limitations and other considerations</span></a> on limitations for more details.</p> </div> <p>Most computers carry out floating point operations in conformance with the so-called IEEE-754 standard. On any real computer, some floating point operations produce results that cannot be expressed as a normal floating point value. For example, try</p> <pre data-language="python">&gt;&gt;&gt; import math
&gt;&gt;&gt; math.exp(1000)
inf
&gt;&gt;&gt; math.exp(1000) / math.exp(1000)
nan
</pre> <p>(The example above will work on many platforms. DEC Alpha may be one exception.) “Inf” is a special, non-numeric value in IEEE-754 that stands for “infinity”, and “nan” means “not a number.” Note that, other than the non-numeric results, nothing special happened when you asked Python to carry out those calculations. That is in fact the default behaviour prescribed in the IEEE-754 standard, and if it works for you, stop reading now.</p> <p>In some circumstances, it would be better to raise an exception and stop processing at the point where the faulty operation was attempted. The <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module is for use in that situation. It provides control over floating point units from several hardware manufacturers, allowing the user to turn on the generation of <code>SIGFPE</code> whenever any of the IEEE-754 exceptions Division by Zero, Overflow, or Invalid Operation occurs. In tandem with a pair of wrapper macros that are inserted into the C code comprising your python system, <code>SIGFPE</code> is trapped and converted into the Python <a class="reference internal" href="exceptions#FloatingPointError" title="FloatingPointError"><code>FloatingPointError</code></a> exception.</p> <p>The <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module defines the following functions and may raise the given exception:</p> <dl class="function"> <dt id="fpectl.turnon_sigfpe">
<code>fpectl.turnon_sigfpe()</code> </dt> <dd>
<p>Turn on the generation of <code>SIGFPE</code>, and set up an appropriate signal handler.</p> </dd>
</dl> <dl class="function"> <dt id="fpectl.turnoff_sigfpe">
<code>fpectl.turnoff_sigfpe()</code> </dt> <dd>
<p>Reset default handling of floating point exceptions.</p> </dd>
</dl> <dl class="exception"> <dt id="fpectl.FloatingPointError">
<code>exception fpectl.FloatingPointError</code> </dt> <dd>
<p>After <a class="reference internal" href="#fpectl.turnon_sigfpe" title="fpectl.turnon_sigfpe"><code>turnon_sigfpe()</code></a> has been executed, a floating point operation that raises one of the IEEE-754 exceptions Division by Zero, Overflow, or Invalid operation will in turn raise this standard Python exception.</p> </dd>
</dl> <h2 id="fpectl-example">
<span class="section-number">29.14.1. </span>Example</h2> <p id="example">The following example demonstrates how to start up and test operation of the <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module.</p> <pre data-language="python">&gt;&gt;&gt; import fpectl
&gt;&gt;&gt; import fpetest
&gt;&gt;&gt; fpectl.turnon_sigfpe()
&gt;&gt;&gt; fpetest.test()
overflow        PASS
FloatingPointError: Overflow

div by 0        PASS
FloatingPointError: Division by zero
  [ more output from test elided ]
&gt;&gt;&gt; import math
&gt;&gt;&gt; math.exp(1000)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
FloatingPointError: in math_1
</pre> <h2 id="fpectl-limitations">
<span class="section-number">29.14.2. </span>Limitations and other considerations</h2> <p id="limitations-and-other-considerations">Setting up a given processor to trap IEEE-754 floating point errors currently requires custom code on a per-architecture basis. You may have to modify <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> to control your particular hardware.</p> <p>Conversion of an IEEE-754 exception to a Python exception requires that the wrapper macros <code>PyFPE_START_PROTECT</code> and <code>PyFPE_END_PROTECT</code> be inserted into your code in an appropriate fashion. Python itself has been modified to support the <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module, but many other codes of interest to numerical analysts have not.</p> <p>The <a class="reference internal" href="#module-fpectl" title="fpectl: Provide control for floating point exception handling. (Unix)"><code>fpectl</code></a> module is not thread-safe.</p> <div class="admonition seealso"> <p class="admonition-title">See also</p> <p>Some files in the source distribution may be interesting in learning more about how this module operates. The include file <code>Include/pyfpe.h</code> discusses the implementation of this module at some length. <code>Modules/fpetestmodule.c</code> gives several examples of use. Many additional examples can be found in <code>Objects/floatobject.c</code>.</p> </div><div class="_attribution">
<p class="_attribution-p">
    © 2001–2020 Python Software Foundation<br/>Licensed under the PSF License.<br/>
https://docs.python.org/3.6/library/fpectl.html
</p>
</div>
